// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Customer struct {
	CustomerID string `json:"customerId"`
	Username   string `json:"username"`
	Email      string `json:"email"`
	Age        int32  `json:"age"`
	MetaData   string `json:"metaData"`
}

type Mutation struct {
}

type NewCustomer struct {
	CustomerID string `json:"customerId"`
	Username   string `json:"username"`
	Email      string `json:"email"`
	Age        int32  `json:"age"`
	MetaData   string `json:"metaData"`
}

type Query struct {
}
